### PR TITLE
Works with new OpenSSL library. Add new flag - strict.

### PR DESCRIPTION
**Pull request by mlojewski-me**

### CODE REVIEW

**Comment by jwhitbeck** [comment]
Hi Marcin,

Thanks for the PR. These changes seem fine. Frankly, it's been a few years since I last looked at this code, so you probably know it a lot better than I do at this point. 

Could you tell me a little bit more about what motivated these changes? The `-strict` flag makes a lot of sense to me, but what is the use-case for `strip_last_n_pw_chars`? What changed with openssl?

**Comment by mlojewski-me** [comment]
Hi John,

1. The `strict` flag is easy to understand and it enforces user to used the same IP address, if the address changes user have to authenticate again.

2. When I wanted to compile your code I got error (Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux):
```
   EVP_MD_CTX mdctx;
              ^~~~~
pam_cookie.c:160:3: warning: implicit declaration of function ‘EVP_MD_CTX_cleanup’ [-Wimplicit-function-declaration]
   EVP_MD_CTX_cleanup(&mdctx);
   ^~~~~~~~~~~~~~~~~~
pam_cookie.c:151:14: warning: unused variable ‘mdctx’ [-Wunused-variable]
   EVP_MD_CTX mdctx;
              ^~~~~
<builtin>: recipe for target 'pam_cookie.o' failed
make: *** [pam_cookie.o] Error 1
```
So i check it and I read that I have to downgrade my OpenSSL library in order to compile this code, I like it better to upgrade your code than to downgrade my library.
I'm planning to add support of multiply hash algorithm (using EVP_get_digestbyname) because now I hardcored sha512 function.

3. About the `strip_last_n_pw_chars` flag. I use your `pam_cookie` on my nginx server along with https://github.com/lojewskimarcin/ngx_http_auth_pam_module.

I want to use HTTP Basic Auth to authenticate users, along with `pam_google_authenticator` which adds support of OTP codes. The problem is that `ngx_http_auth_pam_module` cannot prompt the user for more than just one password.

My pam configuration looks like this:
```
auth	[success=3 default=ignore]	pam_cookie.so auth strip_last_n_pw_chars=6
auth	[success=ok default=1]		pam_google_authenticator.so forward_pass
auth	[success=1 default=ignore]	pam_pgsql.so use_first_pass

auth	requisite			pam_deny.so
auth	required			pam_permit.so
auth	optional			pam_cookie.so cookie touch
```

As you can see first time when I correctly authenticate the pam_google_authenticator gets password + OTP code (pam_cookie only strips code on successful auth), then It strips OTP code (forward_pass flag) and forwards only password to the `pam_pgsql` module, then cookie action of `pam_cookie` module receives only the password.

Next time I request auth `pam_cookie` gets password + OTP code but this time it strips OTP code from request's password and check only the real password in the database, thanks to that I can get authenticated in `pam_cookie`, which I need because authentication in my database takes long time.

**Comment by mlojewski-me** [comment]
Added digest_name config option.

**Comment by jwhitbeck** [comment]
Thanks for the explanations. Would you mind just adding your example to the README? I think that would help others understand the intent of the `strip_last_n_pw_chars` option. I'll merge right aftewards.

Thanks!

**Comment by mlojewski-me** [comment]
Done.

**Comment by jwhitbeck** [comment]
Thanks!

**Pull request merged**
